name: run-json-validation
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f tools/validator/requirements.txt ]; then pip install -r tools/validator/requirements.txt; fi
    - name: Run validator
      run: python tools/validator/validator.py